### ISSUE TITLE
Setting skip_if: :all_blank on collections prevents the nested models from being persisted

### ISSUE THREAD

**Issue by cattekin** [trailblazer/reform#367]
when used on a collection for a `has_many`, `skip_if: :all_blank` is preventing the nested collection from being persisted, even with valid attributes.

for a rails app demoing this: [example rails app](https://github.com/cattekin/reform_collection)

sample collection code which produces this error:

``` ruby
class PostsForm < Reform::Form
  property :body, validates: { presence: true }

  collection :comments, form: CommentsForm,
    skip_if: :all_blank,
    populator: -> (collection:, index:, **) do
      if item = collection[index]
        item
      else
        collection.append(Comment.new)
      end
    end
end
```

**Comment by apotonick** [comment]
Can you give an example what the collection looks before and after the `validate` call, and also paste the incoming params?

**Comment by cattekin** [comment]
Hey @apotonick, I dug into this on Tuesday, main cause looks to be trying to compare strings / symbols in the AllBlank class.

the keys for `options[:input]` are passed in as symbols,
but the names in `options[:binding][:nested].definitions.collect { |dfn| dfn[:name] }` are strings

If you still want the collection before after or params, let me know.
Also happy to do a small PR with a fix.

added the code with comments:
``` ruby
# lib/reform/form/validate.rb
module Skip
  class AllBlank
    include Uber::Callable

    def call(form, options)
      # keys here are passed in as symbols
      params = options[:input]
      # definition names are passed in here as strings
      properties = options[:binding][:nested].definitions.collect { |dfn| dfn[:name] }

      properties.each { |name| params[name].present? and return false }
      true # skip
    end
  end
end
```

**Comment by fran-worley** [comment]
@cattekin a PR with a test case and a fix would be lovely if you're still up for it.

As of Reform 2.2 we moved all rails code to reform-rails so please don't use `.present?` or  other ActiveSupport methods in your PR.

**Comment by cattekin** [comment]
@fran-worley pushed a PR for this.
Let me know if it needs any work

**Comment by emaglio** [comment]
Fixed by https://github.com/trailblazer/reform/pull/392
