### ISSUE TITLE
Manual coercion does not work from a module

### ISSUE THREAD

**Issue by samstickland** [trailblazer/reform#406]
### Complete Description of Issue

Manual coercion inside of a Reform module does not work

### Steps to reproduce

```
module MyFormModule
  include Reform::Form::Module

  property :username

  module InstanceMethods
    def username=(value)
      super(value&.downcase)
    end
  end
end

class MyForm < Reform::Form
  feature Coercion

  include MyFormModule
end

form = MyForm.new(OpenStruct.new)
form.validate(username: 'ABC')
```

### Expected behavior

Setter from form module should be used, e.g. username should become 'abc'

### Actual behavior

Setter from disposable is defined on form, so manual coercion does not happen.

### System configuration
**Reform version**: 2.2.1

**Comment by BroiSatse** [comment]
Did some more digging into the issue we're having. The code above will work just fine, the issue was actually caused by including module within another module. Repro code below:

```
module MyFormModuleA
  include Reform::Form::Module

  property :username

  module InstanceMethods
    def username=(value)
      super(value&.downcase)
    end
  end
end

module MyFormModuleB
  include Reform::Form::Module
  include MyFormModuleA

  # at this time all methods defined in InstanceMethods module are defined directly in MyFormModuleB,
  # so custom setters will be overriden by default setters when this module is included into the actual form.
end

class MyForm < Reform::Form
  include MyFormModuleB
end

form = MyForm.new(OpenStruct.new)
form.validate(username: 'ABC')
form.username #=> 'ABC'
```

**Comment by BroiSatse** [comment]
There are couple of possible solutions here.

First one would be to modify the included hook to check whether form module is included in a module or class, extending InstanceMethods modules in case of the former and including them as now for classes. it is quite dirty.

Cleaner way would be to define new class method in Reform::Form::Module `extends_form` that would handle the merging. This however is not saving a user from including the module and hitting the same issue without reading the correct documentation, so I am not really happy with it as well.

Honestly I think the Reform::Form::Module API is a little bit opaque. Most of developers will be used to define class methods in ClassMethods, InstanceMethods module feels very unnatural for Ruby. I understand the reason behind is more fine-grained control over the inclusion order/method lookup order with properties being defined in a separate modules. I'll try to have a look how this could be redone so we keep the same level of control with more developer-friendly API.

In the meantime I think I'll implement the first solution.

**Comment by fran-worley** [comment]
@BroiSatse for looking into this. I agree with your comments RE the existing API. If you can come up with something better PRs are very much welcome 😸 . 

It's probably worth getting @apotonick involved in the discussion as he's the genius behind it!

**Comment by apotonick** [comment]
We will soon support adding the manual coercion via `:type`, even on top of a Dry type (or whatever type you want).

**Comment by konung** [comment]
I maybe a bit late to the discussion, but here are my two cents. Load order of modules matters. Here is a working example from my code. Using reform 2.3.0 (using Rails)



```ruby
require 'reform/form/dry'
require 'reform/form/coercion'


module Rate::Contract
  module Properties
    include Reform::Form::Module
    include Reform::Form::Coercion
    feature Reform::Form::Dry
    feature Reform::Form::Coercion


    property :name,         type: Types::Coercible::String
    property :code,         type: Types::Coercible::String
    property :amount_cents, type: Types::Form::Int
    property :percentage,   type: Types::Form::Float
    property :meh,          type: Types::Form::Int,        virtual: true, default: 2016

    validation :default do
      required(:name).filled(:str?)
      required(:code).filled(:str?)
    end
  end

  class Create < Reform::Form
    model Rate
    include Properties
  end

  class Update < Create
  end
end


# in console
form = Rate::Contract::Create.new(Rate.new) 
form.validate({name: 123, code: 'xmas122'}) 
form.name #=> "123" cast as string

```

**Comment by apotonick** [comment]
Not *loading* order but **inclusion order**... :wink:

**Comment by konung** [comment]
Way to pick on a non-native speaker... Oh wait... you aren't either. 😳

**Comment by emaglio** [comment]
Really late on this but on branch `2.3.0.rc2` this test https://github.com/trailblazer/reform/blob/v2.3.0.rc2/test/module_test.rb#L53 is passing correctly so I think using `2.3.0` should fix the issue.
It seems that `include Coercion` should be enough without triggering the `feature` call.
