### ISSUE TITLE
Expose raw validation result

### ISSUE THREAD

**Issue by dnd** [trailblazer/reform#410]
There is currently no way to access the raw validation result that is returned from dry-validations, and it contains additional information that can be used to create more complex/detailed error returns. By exposing this value users can still continue to use `Form#errors` for the simple error messages, or they can access the raw result (`Form#validation_result` maybe?) to construct a more elaborate response.

**Comment by fran-worley** [comment]
It would be useful to know what extra data it is that your looking for.

If you're trying to acces hints vs errors or full messages vs standard then oh won't need the raw result. Off the top of my head I can't think what else youd need as your input is essentially form.to_nested_hash...

**Comment by dnd** [comment]
Hints, and errors yes. I'm trying to also get changes made to the MessageSet returned from dry-validation to include additional information in it as well. Ideally I'm looking for a return along the lines of this: https://discuss.dry-rb.org/t/different-data-types-for-errors-on-array-of-hashes/152/3?u=dnd

Yes, I want the errors(messages), and the hints, but I'm also looking for the predicate value to provide more  machine friendly errors messages. So the data structure that Reform uses would have to change completely to support more complex values for hints and messages to have the predicate, and potentially tokens in the future, as right now it's just field/string pairs.

**Comment by apotonick** [comment]
I refactored the errors code last night and we can now transport those raw errors. It will be an array, though, one for every validation group. Is that still helpful, @dnd ?

**Comment by apotonick** [comment]
@dnd See here: https://github.com/trailblazer/reform/blob/nick-simple/lib/reform/contract/errors.rb#L2

**Comment by apotonick** [comment]
Once the dry errors format becomes stable, we could think about exposing it directly via Reform's `Errors`.

**Comment by apotonick** [comment]
You can grab the original Dry errors object with the `Form#to_result` method. It's undocumented and considered private, but will do the trick!

**Comment by dnd** [comment]
@apotonick sorry to dig this up to the dead, but I finally get to work with Trailblazer again. :) `#to_result` almost gets me there. I still have to do `form.to_result.instance_variable_get(:@results)` or `:@failure` to actually get the raw dry-validation data. 

Would you accept a PR to the `2.3.0.rc2` branch to make readers for `@failure` and `@results` on `Reform::Contract::Result`? Maybe even label the readers `raw_failure`, or `raw_results` so that it is explicit that they're not part Reform?

All the data I need is in there to construct the API errors I need. I just don't want to have to reach in an grab instance variables for obvious reasons.

**Comment by apotonick** [comment]
Hey, welcome back! :beers:  It's a good idea to allow exposing the original result. However, I am not super keen to release Reform 2.3 since I've been working on a better form object recently. PR it and maybe we discuss it with @fran-worley ?
