### ISSUE TITLE
Bug or feature? "inherit" option (partially?) ignored when using composition.

### ISSUE THREAD

**Issue by niels** [trailblazer/reform#413]
Using reform 2.2.1 and disposable 0.3.2, let's say we want to share some behaviour across multiple forms. Perhaps it is complicated validation logic or complex functionality to derive some values from others. As a very contrived example, we might sell some products whose price depends on the chosen size:

```ruby
module SizePrice
  include Reform::Form::Module

  property :price
  property :size

  module InstanceMethods
    def price(for_size: size)
      case for_size.to_sym
        when :s then super() * 1
        when :m then super() * 2
        when :l then super() * 3
      end
    end
  end
end
```

Crucially, we overwrite the `price` getter to automatically take into account the form's `size` while also allowing an alternative `for_size` to be passed in. This might be useful e.g. to render a list of size options accompanied by their respective price while at the same time by default returning the price for the persisted size. This works fine when included in a simple form:

```ruby
class TshirtForm < Reform::Form
  include SizePrice
end

Struct.new("Tshirt", :price, :size)
tshirt = Struct::Tshirt.new(2, :m)

form = TshirtForm.new(tshirt)
form.price #=> 4
form.price(for_size: :s) #=> 2
```

Let's say we want to include that same behaviour in a *composed* form as well. We might try to achieve this as follows where the intention is to leave the property definition intact (as it was included) and simply add an `on` option for the composition.

```ruby
class OutfitForm < Reform::Form
  include Reform::Form::Composition
  include SizePrice

  property :price,  inherit: true, on: :tshirt
  property :size,   inherit: true, on: :measurements
end

Struct.new("Measurements", :size)
measurements = Struct::Measurements.new(:l)

form = OutfitForm.new(tshirt: tshirt, measurements: measurements)
form.price #=> 2–but should be 6
form.price(for_size: :s) #=> ArgumentError: wrong number of arguments (given 1, expected 0)
```

As demonstrated, this does not work. It turns out that lib/disposable/twin.rb re-creates the property accessors. While `Disposable::Twin.property` received the `inherit` option, whether or not accessors are crated is keyed off of the `_inherited` option which did *not* get passed in.

The sequence of events is: (1) SizePrice gets included, its `property` calls get executed and set up accessors; (2) SizePrice's InstanceMethods get included, overwriting the property reader–or rather adding a new one in the inheritance chain; (3) OutfitForm's property calls re-add new property accessors, *as if `inherit` had not been specified*. I would not have expected (3) to take place.

To make this work, we have to manually pass the `_inherited` option in addition to `inherit`:

```ruby
class FixedOutfitForm < Reform::Form
  include Reform::Form::Composition
  include SizePrice

  property :price,  inherit: true, _inherited: true, on: :tshirt
  property :size,   inherit: true, _inherited: true, on: :measurements
end

form = FixedOutfitForm.new(tshirt: tshirt, measurements: measurements)
form.price #=> 6
form.price(for_size: :s) #=> 2
```

Is this on purpose? The behaviour strikes me as undesired. At the very least it is unexpected–unless I missed this being documented somewhere.

I did not dare attempting a patch as the inheritance logic and delegation across the various libraries is rather intimidating. I would however be happy to improve the documentation if the above behaviour is by design.

**Comment by fran-worley** [comment]
Hey, thanks for getting in touch and providing such a lovely and clear example.

It's not the sexiest fix but it does the job 😼
