### ISSUE TITLE
uninitialized constant Uber::Options

### ISSUE THREAD

**Issue by kapso** [trailblazer/reform#422]
Seeing the following error

```ruby
NameError: uninitialized constant Uber::Options
2017-01-28T18:28:36.979725+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/reform-2.2.3/lib/reform/form/populator.rb:12
```

According to my `Gemfile.lock` I have `uber (0.1.0)`

**Comment by mensfeld** [comment]
Same for me after update

**Comment by mensfeld** [comment]
@kapso  for now you can fix that by requiring manually uber/options somewhere before you use that:

```ruby
require 'uber/options'
```

**Comment by apotonick** [comment]
Please test `reform/master`.

**Comment by kapso** [comment]
@apotonick yea the above error is fixed in `master`

but now seeing this error -

```
NoMethodError - undefined method `[]' for nil:NilClass:
  simple_form (3.4.0) lib/simple_form/components/errors.rb:41:in `errors_on_attribute'
```

**Comment by mensfeld** [comment]
@apotonick  can't do - using trbr from a gem so only official releases :(

**Comment by apotonick** [comment]
Finally, Reform 2.3 appears on the horizon and should be released in a few days. Then, never ever `uber` and Dry.RB problems.

**Comment by apotonick** [comment]
Please update to Reform 2.2.4, it should do the trick. :wink:

**Comment by mensfeld** [comment]
@apotonick  co can we finally remove uber at all?

**Comment by apotonick** [comment]
Uhm, not entirely, there are still places (e.g. in Cells and Reform) where we use its `inheritable_attr`, but other than that, I extracted logic to separate gems which allows easier API changes without breaking everything.

Does it work for you?

**Comment by mensfeld** [comment]
Yeah - I have uber in only 2 places so I will just remove it one day ;)
