### ISSUE TITLE
With simple_form & enable_active_model_builder_methods, checking for errors on an attribute raises exception

### ISSUE THREAD

**Issue by contentfree** [trailblazer/reform#423]
### Complete Description of Issue
Trying to work around another error related to missing method `to_key` when using the latest reform-rails and reform, we added `config.reform.enable_active_model_builder_methods = true`. That got rid of the `to_key` error. However, a new exception is raised.

### Steps to reproduce
Have a simple_form-powered form and use `config.reform.enable_active_model_builder_methods = true`. 

### Expected behavior
Checking for errors shouldn't raise an exception

### Actual behavior
The following error is raised:

```
Failure/Error: = f.input :name, hint: "The name of the campaign message"

NoMethodError:
  undefined method `messages' for nil:NilClass
# /path/bundler/gems/reform-0b5437cd98f9/lib/reform/errors.rb:15:in `block in <class:Errors>'
# /path/bundler/gems/reform-0b5437cd98f9/lib/reform/errors.rb:9:in `call'
# /path/bundler/gems/reform-0b5437cd98f9/lib/reform/errors.rb:9:in `initialize'
# /path/bundler/gems/reform-0b5437cd98f9/lib/reform/contract/validate.rb:9:in `new'
# /path/bundler/gems/reform-0b5437cd98f9/lib/reform/contract/validate.rb:9:in `errors'
# /path/gems/simple_form-3.4.0/lib/simple_form/components/errors.rb:41:in `errors_on_attribute'
# /path/gems/simple_form-3.4.0/lib/simple_form/components/errors.rb:33:in `errors'
# /path/gems/simple_form-3.4.0/lib/simple_form/components/errors.rb:13:in `has_errors?'
# /path/gems/simple_form-3.4.0/lib/simple_form/components/html5.rb:14:in `html5'
# /path/gems/simple_form-3.4.0/lib/simple_form/wrappers/leaf.rb:19:in `call'
# /path/gems/simple_form-3.4.0/lib/simple_form/wrappers/leaf.rb:19:in `render'
# /path/gems/simple_form-3.4.0/lib/simple_form/wrappers/many.rb:28:in `block in render'
# /path/gems/simple_form-3.4.0/lib/simple_form/wrappers/many.rb:26:in `each'
# /path/gems/simple_form-3.4.0/lib/simple_form/wrappers/many.rb:26:in `render'
# /path/gems/simple_form-3.4.0/lib/simple_form/wrappers/root.rb:15:in `render'
# /path/gems/simple_form-3.4.0/lib/simple_form/form_builder.rb:121:in `input'
# app/concepts/quick_campaign_message/views/form.haml:4:in `block (2 levels) in singleton class'
```

### System configuration
Reform: master (0b5437cd98f9)
Simple_form: 3.4.0

**Comment by contentfree** [comment]
I think the main issue is that simple_form looks at errors which instantiates  `Reform::Contract::Result::Errors` with a nil @result since the contract hasn't been validated yet. 

If @result is nil then the DottedErrors stuff bonks hard.

Ideally, with simple_form, checking for an error on an attribute would return false if validation hasn't ran yet.

**Comment by jeromegn** [comment]
I've just experienced the same thing with Rails' `form_for`. Which seems to attempt and look for errors (calling `#errors`) when creating fields.

**Comment by fran-worley** [comment]
@contentfree This won't work yet as we've not updated reform-rails to work with reform on master. 

checkout https://github.com/trailblazer/reform-rails/tree/reform-master for progress on this. 

I'm going to close this here and re-open in reform-rails as that is where we deal with all rails/active record related issues.

**Comment by lastobelus** [comment]
Many form builders still fail (ex: `rails-bootstrap-forms`), because they assume `object.errors[:attr]` will follow the Rails convention of returning `[]` rather than `nil`

**Comment by apotonick** [comment]
@lastobelus I think these are two "kinda" different things, the problem here is that the form hasn't been validated, yet.

I am more and more tempted to provide a new method `form#to_render` or something that will return a decorated, renderable form that may contain all the nasty hacks and assumptions necessary to make the Rails-based helpers work. I don't want to design our internal code around fixing Rails' bullshit API from 10 years ago, so we might have to go with a dedicated, hacky presentation object.

**Comment by fran-worley** [comment]
I'm closing this as it's covered here: https://github.com/trailblazer/reform-rails/issues/46
