### ISSUE TITLE
NoMethodError (undefined method `name=' for #<Class:0x18a82128> Did you mean?  name):

### ISSUE THREAD

**Issue by agm1988** [trailblazer/reform#425]
I am trying to create a form object with reform

```
class UserForm < Reform::Form
  model User
  include Reform::Form::ActiveModel

  property :name
end
```

and in controller

```
    def new
      @url = users_path
      @form = ::Plant::RipeGroup::RipeGroupForm.new(User.new)
    end
```

```
    def create
      @form = UserForm.new(User.new)
      if @form.validate(params[:user])
        @form.save
      else
        @url = users_path
        # @form.prepopulate!
        render action: :new
      end
    end
```

and when I submit form I get error

```
NoMethodError (undefined method `name=' for #<Class:0x18a82128>
Did you mean?  name):
```

So as I discovered so far it tries to assign attributes not to a model, but to an instance of a class UserForm

**Comment by fran-worley** [comment]
Can you provide a little more info? 
* Reform & reform-rails versions
* full stacktrace

**Comment by fran-worley** [comment]
@agm1988 I'm going to close this as we can't do much to help without the extra info.

I'll reopen and look into it if/ when you can provide the info I requested back in Feb.

Thanks!
