### ISSUE TITLE
Add Lambda/Symbol Support for `writeable`

### ISSUE THREAD

**Issue by svoop** [trailblazer/reform#427]
Unlike `skip_if`, the `writeable` option on a `property` doesn't currently accept a lambda or a symbol (referencing to a method), however, with this addition, something similar to the following scenario becomes possible:

```ruby
# Either: Form with Lambda
class ProductForm < Reform::Form
  property :price, writeable: ->(product) { !product.ordered? }
end

# Or: Form with Symbol
class ProductForm < Reform::Form
  property :price, writeable: :restricted?

  def restricted?
    # some criteria
  end
end

# View (e.g. with form builder from Rails)
f.input :price,
  disabled: f.object.readonly?(:price)
```

In other words: The `writable` option can be used to enable/disable form inputs based on the state of the form (or the underlying model) in a safe way; re-enabling such an input by hacking the form will not result in modifications being persisted. 

It's almost possible to do this with `skip_if`, however, there's one nasty complication: Since validations are run even on skipped properties, things get quite messy.

I'm not sure how to tackle this or whether it's even a desirable addition, please comment!

**Comment by fran-worley** [comment]
Thanks svoop. I think that this would go into disposable, see https://github.com/apotonick/disposable/issues/40

I'm going to close this as it is a duplication, please track the issue in disposable for progress.
