### ISSUE TITLE
2.3.0rc1 seems to break option: form in validation custom predicates

### ISSUE THREAD

**Issue by lastobelus** [trailblazer/reform#431]
Upgrading to 2.3.0rc1 made `option: form` in custom validation predicates cease working.

### Steps to reproduce

```ruby
    class BobForm  < Reform::Form
      property :bob
      validation :default do
        configure do
          option :form
          config.messages_file = '/2007/java/bob-error-messages.yml'
          def bob?(value)
            !form.nil?
          end
        end

        required(:bob).filled(:bob?)
      end
    end

    it "bobs" do
      form = BobForm.new(OpenStruct.new(bob: ""))
      form.validate(bob: "bob")
      expect(form.errors.messages).to be_empty
    end
```

### Expected behavior
Spec passes in 2.2.4

### Actual behavior
Spec fails in 2.3.0rc1. 
Inspection show there is a `form` accessor in the context of the custom predicate, but it returns nil.

**Comment by fran-worley** [comment]
I was about to reply with RTfM but then remembered that I forgot to put this in the manual! 🤣

For performance reasons we no longer inject the form into your schema by default. Instead you need to add an option to your validation block declaration:
with: { form: true }

You won't need to declare option :form anymore as that is done automatically.

There are lots of examples of cool new things added to Reform with dry in the main dry test file:
https://github.com/trailblazer/reform/blob/master/test/validation/dry_validation_test.rb

I'll try and sort the docs out this week!

**Comment by lastobelus** [comment]
cool, thanks above code works using `validation with: {form: true}`

**Comment by moofkit** [comment]
@fran-worley is it possible to configure Reform default schema globally?
In earlier versions we using dirty monkey patch

```ruby
class Reform::Form::Dry::Validations::DrySchema
  module Predicates
    # some custom app predicates
  end

  configure do
    include SessionContainer::CurrentUser

    option :form
    config.messages = :i18n

    predicates(Predicates)
    
    def unique_email?(value)
      !User.where(email: value).where.not(id: form.model.id).exists?
    end

    # some other an application wide predicates
  end
``` 

but now as I see there are no way to do that because for each form instantiate independent `Schema`.
https://github.com/trailblazer/reform/blob/master/lib/reform/form/dry.rb#L26

**Comment by fran-worley** [comment]
Reform looks for a schema class passed into the validation block:
`validation schema: SomeSchema do` .... `end`

If you don't provide one it will create  a new one.

**Comment by contentfree** [comment]
Yeah, but is there a way to make `with: { form: true }` global without having to pass that in every `validation schema: MySchema` block?

**Comment by moofkit** [comment]
@contentfree I'm using dirty monkey patching for this now.. I find "default" feature very useful too.

**Comment by fran-worley** [comment]
I intentionally left this injection as 'opt-in' given that per the dry-v docs end of http://dry-rb.org/gems/dry-validation/basics/working-with-schemas/ injecting dependencies via with requires all the rules to be re-built which is a potential performance issue depending on schema size etc.

Take a good look at why you need form access, I've been running through my code and making use of new dry-v features to really cut down on where I need to inject form. 

Happy to consider allowing you to configure a default with hash until dry have solved the perf issues with injecting dependencies I'd be reluctant to include it by default.
