### ISSUE TITLE
Error messages for dry-v each macros not included in reform `errors.messages`

### ISSUE THREAD

**Issue by fran-worley** [trailblazer/reform#449]
So I can confirm that this is a bug - https://github.com/trailblazer/reform/pull/448/files

The errors are coming though into Reform and it is correctly marked as failed, but the messages are not extracted into `contract.errors.messages`.

@apotonick are you able to take a quick look at why this might be as you wrote the message path traversing stuff...

**Comment by fran-worley** [comment]
Fixed via https://github.com/trailblazer/reform/commit/a7c1bee4d8679fc070c87ff80b47d9a662b08724

**Comment by Tab10id** [comment]
Cool, thanks! :+1:
