### ISSUE TITLE
A strange disposable-related error when trying to initialize a Reform form with a Sequel model

### ISSUE THREAD

**Issue by art-solopov** [trailblazer/reform#455]
### Complete Description of Issue

So I have a Sequel model named Team:

```ruby
class Team < Sequel::Model
end
```

And I have a Reform form to create it:

```ruby
module Teams
  module Contract
    class Create < Reform::Form
      include SystemContainer.import[:database]

      property :code
      property :name

      validation do
        required(:code) { filled? > max_size?(10) }
        required(:name).filled

        validate(code_unique: [:code]) do |code|
          database[:teams].select(:id).where(code: code).nil?
        end
      end
    end
  end
end
```

And I'm trying to initialize it from the console:

```
[1] pry(main)> t = Team.first
{
        :id => 1,
      :code => "UK-MUN",
      :name => "Manchester Unted",
    :active => false
}
[2] pry(main)> Teams::Contract::Create.new(t)
```

### Expected behavior
I expect to receive a Teams::Contract::Create instance correlating to the object `t`.

### Actual behavior
```
NoMethodError: undefined method `code' for #<Hash:0x0000561d854a61b0>
from /home/art-solopov/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/disposable-0.4.3/lib/disposable/expose.rb:32:in `block in accessors!'
```

### System configuration
**Reform version**: 2.2.4

**Comment by apotonick** [comment]
The API the form expects is an object responding to `obj#code`, you are providing a hash (see `Team.first`). Make it an `OpenStruct`?

**Comment by art-solopov** [comment]
Sorry for not making it clear earlier, but `Team.first` is, in fact, a `Team` instance, and responds to `#code`.

```ruby
[1] pry(main)> t = Team.first
{
        :id => 1,
      :code => "UK-MUN",
      :name => "Manchester Unted",
    :active => false
}
[2] pry(main)> t.class
Team < Sequel::Model
[3] pry(main)> t.code
"UK-MUN"
```

**Comment by art-solopov** [comment]
Nevermind, I found the problem by `byebug`-ing into `initialize`.
Apparently, it's caused by dry-auto_inject. It passes the `Team` instance as `kwargs` for some reason.
