### ISSUE TITLE
Share validation methods

### ISSUE THREAD

**Issue by milushov** [trailblazer/reform#459]
Hello, thanks for the gem!

What is the best way for sharing validation methods code? I have a few contracts and validations methods which are the same. How can I extract them into separate modules and include this module later in the contract validation block?

Metacode to explain what I want to get:

```ruby
# my module with methods
module DryValidation
  module ValidationMethods
    extend ActiveSupport::Concern

    included do
      def code_valid?(_)
        ...
      end
    end
  end
end

# operation
class Operation
  ...

  contract do
    feature Reform::Form::Coercion

    property :code, virtual: true, type: Types::Code

    validation(with: { form: true }) do
      configure do
        include ::DryValidation::ValidationMethods
      end

      required(:code).filled(:code_valid?)
    end
  end
end
```

**Comment by fran-worley** [comment]
@milushov Glad you're finding it useful - validation blocks are just dry-validation so you can make use of their code [sharing options](http://dry-rb.org/gems/dry-validation/custom-predicates/). 
Depending on what version of reform you are using you may also be able to ['reuse' schemas](http://dry-rb.org/gems/dry-validation/reusing-schemas/)

We try to keep the github issues to bug reports/ feature request - if you need help using it get in touch via our gitter/ slack channels or speak to the dry-rb guys on their gitter channel or [discussion forum](https://discourse.dry-rb.org/).

**Comment by milushov** [comment]
@fran-worley thank you for the reply, I have updated the question post on [gitter](https://gitter.im/trailblazer/chat?at=5b238a86e87f0c7bee8da4d5), maybe you know the answer as well? :)
