### ISSUE TITLE
Release v2.3

### ISSUE THREAD

**Issue by TylerRick** [trailblazer/reform#470]
### Complete Description of Issue

2.2.4 is latest non-pre-release version on https://rubygems.org/gems/reform

![image](https://user-images.githubusercontent.com/14151/50715607-ee10d300-1032-11e9-9ce6-ecbed383230c.png)

which means Gemfiles that don't explicitly request 2.3.0.rc1 are still getting 2.2.4 even though 2.3 has bug fixes and improvements that users want, and even though the changelog for 2.3.0 says "You can upgrade from 2.2.0 without worries." :smile: 

### Expected behavior

```
⟫ gem install reform
Successfully installed reform-2.3.0
1 gem installed
```

### Actual behavior

```
⟫ gem install reform
Successfully installed reform-2.2.4
1 gem installed
```

**Comment by apotonick** [comment]
Thanks! Here's a discussion why I am refraining from releasing 2.3: https://www.youtube.com/watch?v=6eXDAQpaUV8

You're right, we could indeed release a 2.3 version as a maintenance release but I personally don't want to be responsible for it. :grimacing:

**Comment by Uysim** [comment]
+1

**Comment by oreststetsiak** [comment]
dependency error as version **2.3.0.rc1** is not following a conventions
```
ERROR:  While executing gem ... (Gem::DependencyError)
    Unresolved dependency found during sorting - reform (>= 2.2.0, < 3.0.0) (requested by trailblazer-2.0.7)
```

**Comment by dmitry** [comment]
Looks like released by @seuros :)
Thank your for your work!

**Comment by seuros** [comment]
Dont forget to update reform-rails if you using it.
