### ISSUE TITLE
Validating an existing record

### ISSUE THREAD

**Issue by gr1d99** [trailblazer/reform#472]
### Complete Description of Issue
When I validate an existing record, it fails at first but works the second time.

### Steps to reproduce
```ruby
# My Form
require "reform/form/validation/unique_validator"

class PostForm < Reform::Form
  property :title

  validates :title, unique: true
end
```
Now let's try it in the console

```ruby
# create two posts
post = Post.create title: 'title 1'
Post.create title: 'title 2'

# initialize form with an existing record
form = PostForm.new post
p form.validate(title: 'title 2') # returns true
form.save # saves

# re-initialize the form again
form = PostForm.new post
p form.validate(title: 'title 2') # returns false
```

### Expected behavior
My expectation is that the first validation should return **false** because there is an existing record with a similar name _('title 2')_

### Actual behavior
The first validation returned **true**

### System configuration
**Reform version**:
```ruby
gem 'reform', '2.2.4'
gem 'reform-rails', '0.1.7'
```
### Full Backtrace of Exception (if any)
None

**Comment by gr1d99** [comment]
Update:
[Uniqueness Validation](http://trailblazer.to/gems/reform/validation.html#uniqueness-validation) works fine!, interesting.

**Comment by emaglio** [comment]
@gr1d99 can you please use branch reform `v2.3.0.rc2` and reform-rails `master`?
We are about to release new versions and want to double-check if that is already fixed.
Thanks

**Comment by gr1d99** [comment]
@emaglio I have tested issue using **reform** - `v2.3.0.rc2` and **reform-rails** - `master` and I can't be able to replicate the issue again, my problem has been solved 🙌 🙌 

I guess the issue can be closed for now.
