### ISSUE TITLE
AM error handling issues

### ISSUE THREAD

**Issue by emaglio** [trailblazer/reform#479]
This might have some duplicates in the issues list but I want just to add here to keep track of it.
Here what Sam wrote to me today:
![image](https://user-images.githubusercontent.com/5493507/61719460-3ee4e080-ad65-11e9-9da2-2fae849b2ac4.png)
![image](https://user-images.githubusercontent.com/5493507/61719470-486e4880-ad65-11e9-9f8a-a573d36c0d42.png)
![image](https://user-images.githubusercontent.com/5493507/61719498-5623ce00-ad65-11e9-89a1-99b59a9220c0.png)
https://www.morozov.is/2019/05/31/upgrading-dry-gems.html

**Comment by emaglio** [comment]
Updates from Sam:
![image](https://user-images.githubusercontent.com/5493507/63231307-0994bb00-c25d-11e9-8ca9-48c0da1ebb50.png)
https://github.com/samstickland/reform/tree/2.2.5
https://github.com/samstickland/reform-rails/tree/0.1.8
https://github.com/samstickland/reform-rails/commit/f11a2bc0e8f51a25e8fb7b59bb804c45990f68f5
https://github.com/samstickland/reform-rails/commit/e8b4d863f4b78b66affeead3e2d29f3ec9182002
![image](https://user-images.githubusercontent.com/5493507/63231309-14e7e680-c25d-11e9-8193-f85d1472accd.png)
![image](https://user-images.githubusercontent.com/5493507/63231311-1dd8b800-c25d-11e9-8e5a-e598ed571255.png)

**Comment by samstickland** [comment]
Experimental PRs that revert and fix things to a state that is backwards compatible with reform 2.2 and works with Rails 5.1 and Rails 5.2

https://github.com/trailblazer/reform/pull/490
https://github.com/trailblazer/reform-rails/pull/70

**Comment by emaglio** [comment]
@samstickland do you think we can close this?

**Comment by samstickland** [comment]
Yes. It's not needed now, all the fixes we need are on the master branches.
