### ISSUE TITLE
How to validate JSON object where keys are variable and unknown?

### ISSUE THREAD

**Issue by contentfree** [trailblazer/reform#523]
Consider the following JSON object:

```
{
  "sources": {
    "source1": { "type": "a" },
    "source2": { "type": "b" },
    "another one": { "type": "a" }
  }
}
```

(This structure is useful to ensure unique source identifiers, as opposed to putting objects containing an ID property in an array.)

I'd like to use Reform to validate this such that all values in the `sources` map have a `type` property (and have either `a` or `b`).

How does one accomplish this with Reform?

**Comment by konung** [comment]
Yes, it's possible to validate deeply nested hashes.

You can intelligently parse out incoming data, into a predefined structure using a custom populator: http://trailblazer.to/2.1/docs/reform.html#reform-populators

If the keys are unknown, you just want to validate, then you can use a custom validator with internal logic, me thinks. 
http://trailblazer.to/2.1/docs/reform.html#reform-validation-validation-groups

**Comment by contentfree** [comment]
Interesting ideas, @konung. Thanks for the insight.

**Comment by apotonick** [comment]
Hi @contentfree, Hi @konung this is a feature I will allow in Reform 3 (codename "Transform"). 


How deeply nested is the data structure @contentfree ?
