### ISSUE TITLE
`self` in default value for properties is broken when Reform 2.6 is with trailblazer-context

### ISSUE THREAD

**Issue by samstickland** [trailblazer/reform#530]
### Complete Description of Issue

The value of `self` in a property block is resolving to the Class of the form (not the instance) when reform 2.6 is used in a project that also has trailblazer-context included.

This does not happen with reform 2.5 plus trailblazer-context, or with reform 2.6 just used by itself

### Steps to reproduce

```ruby

class MyForm < Reform::Form
  property :my_property, virtual: true, default: -> { puts self; my_method }

  def my_method
    :foobar
  end
end

MyForm.new(nil).my_property
```

### Expected behavior
`self` should resolve to the instance of the form. The default value of `my_property` should be `:foobar`

```
> MyForm.new(nil).my_property
#<MyForm:0x00007f90bcd722c0>
=> :foobar
```

### Actual behavior

`self` resolves to the MyForm class, not the instance, meaning the method cannot be called:

```
irb(main):009:0> my_form = MyForm.new(nil).my_property
MyForm
Traceback (most recent call last):
        3: from (irb):8
        2: from (irb):8:in `new'
        1: from (irb):2:in `block in <class:MyForm>'
NameError (undefined local variable or method `my_method' for MyForm:Class)
Did you mean?  method
```

### System configuration
**Reform version**: 2.6.0

**Comment by yogeshjain999** [comment]
@samstickland I tried to reproduce it by creating new rails app but couldn't reproduce it.

Both gems are independent of each other, I wonder how they can cause such issue. How're they being dependent in your case ? Could you please create a reproducible test for it ?

**Comment by samstickland** [comment]
@yogeshjain999 As requested here is a repo that demonstrates the problem:

https://github.com/samstickland/reform-trailblazer-context-issue

Github defaulted the primary branch to be called 'main' btw.

There's a form in `app/forms/my_form.rb` and a failing test for that form, using minitest: `bundle exec rake test`

The test will pass if you do either of these things:

* remove trailblazer-context from Gemfile
* downgrade reform to 2.5.0

**Comment by samstickland** [comment]
@yogeshjain999 I had to add some more trailblazer gems to the Gemfile to make the problem come back. I'm pushed that to the repo, I'm not sure which of the gems that has been added is causing the interaction that leads to the problem.

**Comment by yogeshjain999** [comment]
@samstickland The issue was in `trailblazer-activity` where it was using old `trailblazer-context` gem to load `Trailblazer::Option`, causing the conflict.

Release [trailblazer-activity-0.12.2](https://github.com/trailblazer/trailblazer-activity/releases/tag/v0.12.2 ) fixes it 🍻
